In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import StackingClassifier

# Load pre-trained models
lr = joblib.load('Logistic_r_model.pkl')   # Logistic Regression model
nb = joblib.load('Multinomial Naive Baye_model.pkl')  # Naive Bayes model 
print("Models loaded successfully.")


Models loaded successfully.


In [5]:
# Define Stacking Classifier using loaded models
stacking_clf = StackingClassifier(
    estimators=[('nb', nb), ('lr', lr)],  # Use pre-trained models
    final_estimator=LogisticRegression(random_state=42),
    stack_method='predict_proba'  # Use probabilities for meta-model
)


In [9]:
# Train the stacking classifier on the full training dataset
stacking_clf.fit(x_train, y_train)
print("Stacking classifier trained successfully.")


Stacking classifier trained successfully.


In [ ]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_lr))

In [13]:
from sklearn.metrics import accuracy_score

# Accuracy on training data
train_accuracy = stacking_clf.score(x_train, y_train)
print(f"Training Accuracy: {train_accuracy:.2f}")

# Predict and calculate accuracy on testing data
y_test_pred = stacking_clf.predict(x_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Testing Accuracy: {test_accuracy:.2f}")


Training Accuracy: 0.89
Testing Accuracy: 0.88


In [14]:
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))


Classification Report:


c:\Users\This PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\This PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


                                                          precision    recall  f1-score   support

                               abdominal aortic aneurysm       1.00      1.00      1.00        20
                                        abdominal hernia       0.97      1.00      0.99        67
                                         abscess of nose       0.81      0.88      0.85        59
                                     abscess of the lung       1.00      1.00      1.00        11
                                  abscess of the pharynx       0.96      0.92      0.94        77
                                    acanthosis nigricans       0.91      1.00      0.95        10
                                               acariasis       1.00      1.00      1.00         9
                                               achalasia       0.92      0.71      0.80        17
                                                    acne       0.71      0.88      0.78       104
                   

c:\Users\This PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
# Save the trained stacking classifier
joblib.dump(stacking_clf, 'stacking_clf_model.pkl')
print("Stacking Classifier model saved successfully at models/stacking_clf_model.pkl.")


Stacking Classifier model saved successfully at models/stacking_clf_model.pkl.


In [2]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
data = pd.read_csv('Updated_Dataset.csv')

In [4]:
data.head(5)

diseases  anxiety and nervousness  depression  shortness of breath  \
0  panic disorder                        1           0                    1   
1  panic disorder                        0           0                    1   
2  panic disorder                        1           1                    1   
3  panic disorder                        1           0                    0   
4  panic disorder                        1           1                    0   

   depressive or psychotic symptoms  sharp chest pain  dizziness  insomnia  \
0                                 1                 0          0         0   
1                                 1                 0          1         1   
2                                 1                 0          1         1   
3                                 1                 0          1         1   
4                                 0                 0          0         1   

   abnormal involuntary movements  chest tightness  ...  \
0                               0                1  ...   
1                               0                0  ...   
2                               0                0  ...   
3                               1                0  ...   
4                               1                1  ...   

   stuttering or stammering  problems with orgasm  nose deformity  \
0                         0                     0               0   
1                         0                     0               0   
2                         0                     0               0   
3                         0                     0               0   
4                         0                     0               0   

   lump over jaw  sore in nose  hip weakness  back swelling  \
0              0             0             0              0   
1              0             0             0              0   
2              0             0             0              0   
3              0             0             0              0   
4              0             0             0              0   

   ankle stiffness or tightness  ankle weakness  neck weakness  
0                             0               0              0  
1                             0               0              0  
2                             0               0              0  
3                             0               0              0  
4                             0               0              0  

[5 rows x 378 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246945 entries, 0 to 246944
Columns: 378 entries, diseases to neck weakness
dtypes: int64(377), object(1)
memory usage: 712.2+ MB


In [5]:
# Dataset Duplicate Value Count
dup = data.duplicated().sum()
print(f'Number of duplicated rows are {dup}')

Number of duplicated rows are 57298


In [6]:
# Missing Values/Null Values Count
data.isnull().sum()

diseases                            0
anxiety and nervousness             0
depression                          0
shortness of breath                 0
depressive or psychotic symptoms    0
                                   ..
hip weakness                        0
back swelling                       0
ankle stiffness or tightness        0
ankle weakness                      0
neck weakness                       0
Length: 378, dtype: int64

In [7]:
data.shape

(246945, 378)

In [29]:
data = data.drop_duplicates()
data=data.reset_index(drop=True)

In [8]:
data.shape

(246945, 378)

In [31]:
data.tail()

diseases  anxiety and nervousness  depression  \
189642  open wound of the nose                        0           0   
189643  open wound of the nose                        0           0   
189644  open wound of the nose                        0           0   
189645  open wound of the nose                        0           0   
189646  open wound of the nose                        0           0   

        shortness of breath  depressive or psychotic symptoms  \
189642                    0                                 0   
189643                    0                                 0   
189644                    0                                 0   
189645                    0                                 0   
189646                    0                                 0   

        sharp chest pain  dizziness  insomnia  abnormal involuntary movements  \
189642                 0          0         0                               0   
189643                 0          0         0                               0   
189644                 0          0         0                               0   
189645                 0          0         0                               0   
189646                 0          0         0                               0   

        chest tightness  ...  stuttering or stammering  problems with orgasm  \
189642                0  ...                         0                     0   
189643                0  ...                         0                     0   
189644                0  ...                         0                     0   
189645                0  ...                         0                     0   
189646                0  ...                         0                     0   

        nose deformity  lump over jaw  sore in nose  hip weakness  \
189642               0              0             0             0   
189643               0              0             0             0   
189644               0              0             0             0   
189645               0              0             0             0   
189646               0              0             0             0   

        back swelling  ankle stiffness or tightness  ankle weakness  \
189642              0                             0               0   
189643              0                             0               0   
189644              0                             0               0   
189645              0                             0               0   
189646              0                             0               0   

        neck weakness  
189642              0  
189643              0  
189644              0  
189645              0  
189646              0  

[5 rows x 378 columns]

In [8]:
data.memory_usage(deep=True).sum()/(1024**2)

np.float64(727.8430681228638)

In [33]:
data['diseases'].unique()

array(['panic disorder', 'vocal cord polyp', 'turner syndrome',
       'cryptorchidism', 'poisoning due to ethylene glycol',
       'atrophic vaginitis', 'fracture of the hand',
       'cellulitis or abscess of mouth', 'eye alignment disorder',
       'headache after lumbar puncture', 'pyloric stenosis',
       'salivary gland disorder', 'osteochondrosis', 'injury to the knee',
       'metabolic disorder', 'vaginitis', 'sick sinus syndrome',
       'tinnitus of unknown cause', 'glaucoma', 'eating disorder',
       'transient ischemic attack', 'pyelonephritis',
       'rotator cuff injury', 'chronic pain disorder',
       'problem during pregnancy', 'liver cancer', 'atelectasis',
       'injury to the hand', 'choledocholithiasis', 'injury to the hip',
       'cirrhosis', 'thoracic aortic aneurysm', 'subdural hemorrhage',
       'diabetic retinopathy', 'fibromyalgia', 'ischemia of the bowel',
       'fetal alcohol syndrome', 'peritonitis', 'injury to the abdomen',
       'acute pancreati

In [34]:
data.shape

(189647, 378)

In [35]:
data['diseases'].nunique()

773

In [9]:
pd.set_option('display.max_rows', None)
data['diseases'].value_counts()

diseases
cystitis                                                    1219
nose disorder                                               1218
vulvodynia                                                  1218
complex regional pain syndrome                              1217
spondylosis                                                 1216
vaginal cyst                                                1215
esophagitis                                                 1215
peripheral nerve disorder                                   1215
hypoglycemia                                                1215
conjunctivitis due to allergy                               1215
gastrointestinal hemorrhage                                 1214
diverticulitis                                              1214
acute bronchitis                                            1213
infectious gastroenteritis                                  1212
fungal infection of the hair                                1212
sprain or strain

In [10]:
data.diseases.value_counts().loc[lambda x : x <= 5].reset_index()

diseases  count
0                                      pelvic fistula      5
1                                    friedrich ataxia      5
2                                      cryptorchidism      5
3                     hyperosmotic hyperketotic state      5
4                                      histoplasmosis      5
5                              von willebrand disease      5
6                                       spherocytosis      5
7                                vitamin a deficiency      5
8                                      uterine cancer      5
9   syndrome of inappropriate secretion of adh (si...      4
10                                             scurvy      4
11                           open wound of the finger      4
12                                    intussusception      4
13                         open wound of the shoulder      4
14                             open wound of the hand      4
15                                meckel diverticulum      4
16                                   oral leukoplakia      4
17                                        amyloidosis      4
18                                   dumping syndrome      4
19                                     hyperlipidemia      3
20                                       dengue fever      3
21                              necrotizing fasciitis      3
22                         connective tissue disorder      3
23                                       lymphangitis      3
24                            primary thrombocythemia      3
25                             open wound of the face      3
26                            dislocation of the knee      3
27                                            obesity      3
28                         dislocation of the patella      3
29                          open wound of the abdomen      3
30                                    hemochromatosis      3
31                                     adrenal cancer      3
32                                 esophageal varices      3
33                                     sporotrichosis      3
34                           myelodysplastic syndrome      3
35                                cat scratch disease      3
36                                    rheumatic fever      2
37                                 carcinoid syndrome      2
38                              hashimoto thyroiditis      2
39       human immunodeficiency virus infection (hiv)      2
40                            diabetic kidney disease      2
41                              open wound of the jaw      2
42                                    turner syndrome      1
43                       rocky mountain spotted fever      1
44                            open wound of the cheek      1
45                                high blood pressure      1
46                           open wound due to trauma      1
47                            open wound of the chest      1
48                                 huntington disease      1
49                             open wound of the knee      1
50                           foreign body in the nose      1
51                                           diabetes      1
52                                        thalassemia      1
53                                        heat stroke      1
54                                       gas gangrene      1
55                                      typhoid fever      1
56                             open wound of the head      1
57                                        myocarditis      1
58                                      chronic ulcer      1
59                             hypergammaglobulinemia      1
60                                     kaposi sarcoma      1

In [7]:
X= data.drop("diseases", axis=1)
y= data['diseases']

In [19]:
X

In [ ]:
y

0                 panic disorder
1                 panic disorder
2                 panic disorder
3                 panic disorder
4                 panic disorder
                   ...          
246937    open wound of the nose
246938    open wound of the nose
246941    open wound of the nose
246943    open wound of the nose
246944    open wound of the nose
Name: diseases, Length: 189647, dtype: object

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split data with stratification using the original target variable
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# You can now use x_train, x_test, y_train, y_test for training and evaluation


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Initialize the Logistic Regression model
lr_model = LogisticRegression()

# Train the model on the training set
lr_model.fit(x_train, y_train)

# Make predictions on the training set
y_train_pred_lr = lr_model.predict(x_train)
# Make predictions on the testing set
y_test_pred_lr = lr_model.predict(x_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_lr))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_lr))


Training Accuracy: 0.87630848974468
Testing Accuracy: 0.8654761181639636


In [14]:
 # Display confusion matrix and classification report for testing set
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_lr))


Confusion Matrix:
[[ 20   0   0 ...   0   0   0]
 [  0  80   0 ...   0   0   0]
 [  0   0  50 ...   0   0   0]
 ...
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   0 105   0]
 [  0   0   0 ...   0   0   2]]

Classification Report:
                                                          precision    recall  f1-score   support

                               abdominal aortic aneurysm       0.74      1.00      0.85        20
                                        abdominal hernia       0.92      0.99      0.95        81
                                         abscess of nose       0.89      0.86      0.88        58
                                     abscess of the lung       1.00      1.00      1.00         6
                                  abscess of the pharynx       0.94      0.98      0.96        63
                                    acanthosis nigricans       0.86      1.00      0.92         6
                                               acariasis       0.83      1.00 

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
import numpy as np

# Initialize the Random Forest model with optimized parameters
rf_model = RandomForestClassifier(
    n_estimators=300,  # Fewer trees to save memory
    max_depth=40,      # Lower max depth to reduce complexity
    max_features="sqrt", 
    class_weight='balanced', 
    n_jobs=-1, 
    random_state=42
)
# Train the model on the full dataset
rf_model.fit(x_train, y_train)

# Make predictions on the training set
y_train_pred_rf = rf_model.predict(x_train)
# Make predictions on the testing set
y_test_pred_rf = rf_model.predict(x_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_rf))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_rf))


MemoryError: Unable to allocate 883. MiB for an array with shape (149710, 1, 773) and data type float64

In [ ]:
# from imblearn.under_sampling import TomekLinks
# from collections import Counter
# import pandas as pd
# import time



# # Create the TomekLinks object
# tl = TomekLinks()

# start_time = time.time()


# # Apply Tomek Links under-sampling
# X_resampled, y_resampled = tl.fit_resample(X, y)

# # Check the class distribution after applying Tomek Links
# print(f'Original dataset shape: {Counter(y)}')
# print(f'Resampled dataset shape: {Counter(y_resampled)}')

# # Convert back to DataFrame if needed
# data_resampled = pd.concat([pd.DataFrame(X_resampled, columns=X.columns), pd.DataFrame(y_resampled, columns=['target'])], axis=1)


# end_time = time.time()

# print(f"Time taken: {end_time - start_time} seconds")

Original dataset shape: Counter({'cystitis': 1219, 'vulvodynia': 1218, 'nose disorder': 1218, 'complex regional pain syndrome': 1217, 'spondylosis': 1216, 'hypoglycemia': 1215, 'conjunctivitis due to allergy': 1215, 'vaginal cyst': 1215, 'esophagitis': 1215, 'peripheral nerve disorder': 1215, 'gastrointestinal hemorrhage': 1214, 'diverticulitis': 1214, 'acute bronchitis': 1213, 'infectious gastroenteritis': 1212, 'pneumonia': 1212, 'fungal infection of the hair': 1212, 'sprain or strain': 1212, 'spontaneous abortion': 1212, 'gout': 1211, 'marijuana abuse': 1210, 'arthritis of the hip': 1210, 'strep throat': 1210, 'injury to the arm': 1209, 'liver disease': 1209, 'bursitis': 1208, 'acute pancreatitis': 1207, 'spinal stenosis': 1207, 'eczema': 1207, 'injury to the leg': 1206, 'noninfectious gastroenteritis': 1206, 'benign prostatic hyperplasia (bph)': 1206, 'acute bronchiolitis': 1204, 'cholecystitis': 1204, 'anxiety': 1198, 'obstructive sleep apnea (osa)': 1196, 'concussion': 1191, 'den

Time taken: 1393.4653866291046 seconds


In [40]:
original_rows = X.shape[0]
resampled_rows = X_resampled.shape[0]

# reduction in rows
rows_removed = original_rows - resampled_rows
print(f'Original number of rows: {original_rows}')
print(f'Number of rows after resampling: {resampled_rows}')
print(f'Number of rows removed: {rows_removed}')


Original number of rows: 189647
Number of rows after resampling: 189589
Number of rows removed: 58


In [48]:
from sklearn.utils import resample
import pandas as pd

# Define the maximum number of samples per class
max_samples = 500

# Function to downsample classes with more than max_samples
def downsample_class(group):
    if len(group) > max_samples:
        return resample(group, replace=False, n_samples=max_samples, random_state=42)
    return group

# Apply the downsampling to each class
data_resampled = data.groupby('diseases').apply(downsample_class).reset_index(drop=True)

# Separate features and target again
X_resampled = data_resampled.drop('diseases', axis=1)
y_resampled = data_resampled['diseases']

# Check the class distribution after downsampling
print(f'Original dataset shape: {Counter(y)}')

print(f'Resampled dataset shape: {Counter(y_resampled)}')

# Optional: Save the resampled dataset to a new CSV file
#data_resampled.to_csv('resampled_dataset.csv', index=False)


Original dataset shape: Counter({'cystitis': 1219, 'vulvodynia': 1218, 'nose disorder': 1218, 'complex regional pain syndrome': 1217, 'spondylosis': 1216, 'hypoglycemia': 1215, 'conjunctivitis due to allergy': 1215, 'vaginal cyst': 1215, 'esophagitis': 1215, 'peripheral nerve disorder': 1215, 'gastrointestinal hemorrhage': 1214, 'diverticulitis': 1214, 'acute bronchitis': 1213, 'infectious gastroenteritis': 1212, 'pneumonia': 1212, 'fungal infection of the hair': 1212, 'sprain or strain': 1212, 'spontaneous abortion': 1212, 'gout': 1211, 'marijuana abuse': 1210, 'arthritis of the hip': 1210, 'strep throat': 1210, 'injury to the arm': 1209, 'liver disease': 1209, 'bursitis': 1208, 'acute pancreatitis': 1207, 'spinal stenosis': 1207, 'eczema': 1207, 'injury to the leg': 1206, 'noninfectious gastroenteritis': 1206, 'benign prostatic hyperplasia (bph)': 1206, 'acute bronchiolitis': 1204, 'cholecystitis': 1204, 'anxiety': 1198, 'obstructive sleep apnea (osa)': 1196, 'concussion': 1191, 'den

In [42]:
original_rows = X.shape[0]
resampled_rows = X_resampled.shape[0]

# reduction in rows
rows_removed = original_rows - resampled_rows
print(f'Original number of rows: {original_rows}')
print(f'Number of rows after resampling: {resampled_rows}')
print(f'Number of rows removed: {rows_removed}')

Original number of rows: 189647
Number of rows after resampling: 138295
Number of rows removed: 51352


In [49]:
#split data
x_train,x_test,y_train,y_test=train_test_split(X_resampled, y_resampled,test_size=0.2,random_state=42 )

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target variable
y_encoded = label_encoder.fit_transform(y)

In [50]:
#split data
x_train,x_test,y_train,y_test=train_test_split(X,y_encoded,test_size=0.2,random_state=42 )

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Initialize the Logistic Regression model
lr_model = LogisticRegression()

# Train the model on the training set
lr_model.fit(x_train, y_train)

# Make predictions on the training set
y_train_pred_lr = lr_model.predict(x_train)
# Make predictions on the testing set
y_test_pred_lr = lr_model.predict(x_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_lr))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_lr))

Training Accuracy: 0.848843570595253
Testing Accuracy: 0.834748220406011


In [42]:
 # Display confusion matrix and classification report for testing set
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_lr))


Confusion Matrix:
[[ 4  0  0 ...  0  0  0]
 [ 0 47  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 59]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.80      0.89         5
           1       0.87      0.96      0.91        49
           2       0.79      0.76      0.77        29
           3       0.00      0.00      0.00         1
           4       0.63      0.88      0.73        25
           5       1.00      0.50      0.67         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         4
           8       0.82      0.74      0.78        82
           9       0.95      0.70      0.80       155
          10       0.89      0.93      0.91       238
          11       0.90      0.64      0.74       247
          12       0.72      0.82      0.77       166
          14       0.27      0.20      0.23 

In [45]:
X_test.shape,X_train.shape,y_test.shape,y_train.shape


(138295,)