In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# from imblearn.under_sampling import TomekLinks
# from collections import Counter
# import pandas as pd



# # Create the TomekLinks object
# tl = TomekLinks()



# # Apply Tomek Links under-sampling
# X_resampled, y_resampled = tl.fit_resample(X, y)


# print(f"Time taken: {end_time - start_time} seconds")

# original_rows = X.shape[0]
# resampled_rows = X_resampled.shape[0]

# # reduction in rows
# rows_removed = original_rows - resampled_rows
# print(f'Original number of rows: {original_rows}')
# print(f'Number of rows after resampling: {resampled_rows}')
# print(f'Number of rows removed: {rows_removed}')

In [4]:
# df_resampled = pd.DataFrame(X_resampled,columns= X.columns)
# df_resampled['diseases'] = y_resampled

# df_resampled.to_csv('resampled_dataset.csv', index = False)
# print ("data saved successfully")

In [5]:
# df_resampled.shape

In [6]:
# X= X_resampled
# y= y_resampled

# WORKING ON NEW DATASET


In [4]:
# import pandas as pd

# # Load your dataset
# dataset_path = 'resampled_dataset.csv'
# data = pd.read_csv(dataset_path)

# # Find diseases with 20 or fewer entries
# diseases_to_duplicate = data['diseases'].value_counts().loc[lambda x: x <= 50].reset_index()
# diseases_to_duplicate.columns = ['diseases', 'count']

# # For each disease, duplicate entries until there are 10 in total
# rows_to_add = []

# for _, row in diseases_to_duplicate.iterrows():
#     disease_name = row['diseases']
#     current_count = row['count']
    
#     # Find rows for this disease
#     disease_rows = data[data['diseases'] == disease_name]
    
#     # Calculate how many more rows to add
#     rows_needed = 100 - current_count
    
#     # Duplicate the disease rows
#     duplicated_rows = disease_rows.sample(n=rows_needed, replace=True)
    
#     # Add them to the list of rows to append
#     rows_to_add.append(duplicated_rows)

# # Concatenate the new rows to the original dataset
# new_data = pd.concat([data] + rows_to_add, ignore_index=True)

# # Save the updated dataset
# output_dataset_path = 'Final_Updated__Dataset.csv'
# new_data.to_csv(output_dataset_path, index=False)

# print(f"Added rows for diseases with fewer than 20 entries. New dataset saved to {output_dataset_path}.")



Added rows for diseases with fewer than 20 entries. New dataset saved to Final_Updated__Dataset.csv.


In [3]:
data1 = pd.read_csv('Final_Updated__Dataset.csv')
data1.head(5)

anxiety and nervousness  depression  shortness of breath  \
0                        0           0                    1   
1                        0           0                    1   
2                        0           0                    0   
3                        0           0                    1   
4                        0           0                    1   

   depressive or psychotic symptoms  sharp chest pain  dizziness  insomnia  \
0                                 0                 0          0         0   
1                                 0                 0          0         0   
2                                 0                 0          0         0   
3                                 0                 0          0         0   
4                                 0                 0          0         0   

   abnormal involuntary movements  chest tightness  palpitations  ...  \
0                               0                0             1  ...   
1                               0                0             1  ...   
2                               0                0             1  ...   
3                               0                0             1  ...   
4                               0                0             1  ...   

   problems with orgasm  nose deformity  lump over jaw  sore in nose  \
0                     0               0              0             0   
1                     0               0              0             0   
2                     0               0              0             0   
3                     0               0              0             0   
4                     0               0              0             0   

   hip weakness  back swelling  ankle stiffness or tightness  ankle weakness  \
0             0              0                             0               0   
1             0              0                             0               0   
2             0              0                             0               0   
3             0              0                             0               0   
4             0              0                             0               0   

   neck weakness                   diseases  
0              0  abdominal aortic aneurysm  
1              0  abdominal aortic aneurysm  
2              0  abdominal aortic aneurysm  
3              0  abdominal aortic aneurysm  
4              0  abdominal aortic aneurysm  

[5 rows x 378 columns]

In [4]:
# Dataset Duplicate Value Count
dup = data1.duplicated().sum()
print(f'Number of duplicated rows are {dup}')

Number of duplicated rows are 30859


In [5]:
pd.set_option('display.max_rows', None)
data1['diseases'].value_counts()

diseases
urinary tract obstruction                                   500
prostatitis                                                 500
hemangioma                                                  500
iron deficiency anemia                                      500
drug reaction                                               500
ischemic heart disease                                      500
conduct disorder                                            500
appendicitis                                                500
fracture of the leg                                         500
pelvic inflammatory disease                                 500
rosacea                                                     500
labyrinthitis                                               500
hypertensive heart disease                                  500
schizophrenia                                               500
corneal disorder                                            500
sciatica                       

In [6]:
data1['diseases'].nunique()

773

In [7]:
X= data1.drop("diseases", axis=1)
y= data1['diseases']

In [8]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split data without stratification
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target variable
y_encoded = label_encoder.fit_transform(y)

# Split data with stratification using the encoded target variable
x_train, x_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# You can now use x_train, x_test, y_train, y_test for training and evaluation



#  Logistic Regression model

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split data with stratification using the original target variable
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# You can now use x_train, x_test, y_train, y_test for training and evaluation


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Initialize the Logistic Regression model
lr_model = LogisticRegression()

# Train the model on the training set
lr_model.fit(x_train, y_train)

# Make predictions on the training set
y_train_pred_lr = lr_model.predict(x_train)
# Make predictions on the testing set
y_test_pred_lr = lr_model.predict(x_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_lr))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_lr))

Training Accuracy: 0.8752722262552037
Testing Accuracy: 0.8630222222222222


In [10]:
 # Display confusion matrix and classification report for testing set
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_lr))


Confusion Matrix:
[[19  0  0 ...  0  0  0]
 [ 0 51  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 56  0]
 [ 0  0  0 ...  0  0 20]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.93        20
           1       0.96      0.96      0.96        53
           2       1.00      0.63      0.78        30
           3       1.00      1.00      1.00        20
           4       0.79      0.91      0.85        33
           5       0.77      0.85      0.81        20
           6       0.77      0.85      0.81        20
           7       0.67      0.90      0.77        20
           8       0.68      0.79      0.73        61
           9       0.94      0.65      0.77       100
          10       0.90      0.92      0.91        98
          11       0.94      0.62      0.75        97
          12       0.75      0.71      0.73        98
          13       0.43      1.00      0.61 

# Random Forest model with some default parameters

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
import numpy as np



# Initialize the Random Forest model with some default parameters
rf_model = RandomForestClassifier(n_estimators=250, max_depth=30, max_features="sqrt", class_weight='balanced', n_jobs=-1)

# Train the model on the full dataset
rf_model.fit(x_train, y_train)

# Make predictions on the training set
y_train_pred_rf = rf_model.predict(x_train)
# Make predictions on the testing set
y_test_pred_rf = rf_model.predict(x_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_rf))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_rf))


Training Accuracy: 0.8248489619729149
Testing Accuracy: 0.7592612249230443


#  Naive Bayes

In [115]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np

# Define parameter grid for GridSearchCV
param_grid = {
    'alpha': [0.01, 0.02, 0.05],
    'fit_prior': [True, False]
}

# Initialize the Naive Bayes model
nb_model1 = MultinomialNB()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=nb_model1, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)

# Fit the model with GridSearchCV
grid_search.fit(x_train, y_train)

# Get the best hyperparameters
best_nb_model_New = grid_search.best_estimator_

# Make predictions with the best model
y_train_pred_nb = best_nb_model_New.predict(x_train)
y_test_pred_nb = best_nb_model_New.predict(x_test)

# Evaluate the model's performance
print("Best Parameters found by GridSearchCV:", grid_search.best_params_)
print("Naive Bayes (Tuned):")
print(f"Training Accuracy: {accuracy_score(y_train, y_train_pred_nb):.4f}")
print(f"Testing Accuracy: {accuracy_score(y_test, y_test_pred_nb):.4f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_test_pred_nb))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred_nb))


Best Parameters found by GridSearchCV: {'alpha': 0.01, 'fit_prior': True}
Naive Bayes (Tuned):
Training Accuracy: 0.8586
Testing Accuracy: 0.8553

Confusion Matrix:
 [[16  0  0 ...  0  0  0]
 [ 0 47  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 56  0]
 [ 0  0  0 ...  0  0 20]]

Classification Report:
                                                           precision    recall  f1-score   support

                               abdominal aortic aneurysm       1.00      0.80      0.89        20
                                        abdominal hernia       1.00      0.89      0.94        53
                                         abscess of nose       1.00      0.63      0.78        30
                                     abscess of the lung       1.00      1.00      1.00        20
                                  abscess of the pharynx       0.88      0.85      0.86        33
                                    acanthosis nigricans       0

# DNN with Batch Normalization and Dropout.

In [18]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout



# Encode the target labels (diseases)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data with stratification to maintain class balance
x_train, x_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded)

# Calculate class weights
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_encoded), y=y_encoded)
class_weight_dict = dict(enumerate(class_weights))

# Build the Sequential DNN Model
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dropout(0.5))  # Dropout to prevent overfitting

# Hidden layers
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

# Output layer for 773 diseases
model.add(Dense(773, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model with class weights
history = model.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), class_weight=class_weight_dict)

# Predictions on the test set
y_pred = model.predict(x_test)

# Get accuracy for training and testing
train_accuracy = model.evaluate(x_train, y_train, verbose=0)[1]
test_accuracy = model.evaluate(x_test, y_test, verbose=0)[1]

# Print accuracies
print(f'Training Accuracy: {train_accuracy * 100:.2f}%')
print(f'Testing Accuracy: {test_accuracy * 100:.2f}%')

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, np.argmax(y_pred, axis=1)))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, np.argmax(y_pred, axis=1)))


Epoch 1/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.0948 - loss: 5.4155 - val_accuracy: 0.7168 - val_loss: 1.1858
Epoch 2/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.4109 - loss: 2.1721 - val_accuracy: 0.7835 - val_loss: 0.8006
Epoch 3/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.5111 - loss: 1.6577 - val_accuracy: 0.7994 - val_loss: 0.6917
Epoch 4/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.5619 - loss: 1.4184 - val_accuracy: 0.8133 - val_loss: 0.6292
Epoch 5/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.5897 - loss: 1.3078 - val_accuracy: 0.8149 - val_loss: 0.6110
Epoch 6/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.6087 - loss: 1.2244 - val_accuracy: 0.8210 - val_loss: 0.5795
Epoch 7/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.6238 - loss: 1.1754 - val_accuracy: 0.8241 - val_loss: 0.5614
Epoch 8/50
1846/1846 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.6323 - loss: 1.1487 

Saving model

In [11]:
import joblib

# Save the trained LOgistic model
joblib.dump(lr_model,'lr_model1.pkl')
print("Logistic model saved successfully.")

Logistic model saved successfully.


In [116]:
import joblib

# Save the trained LOgistic model
joblib.dump(best_nb_model_New,'Multinomial Naive Baye_model.pkl')
print("Multinomial Naive Bayes model saved successfully.")

Multinomial Naive Bayes model saved successfully.


loading the model

In [79]:
import joblib

# Load the saved logistics  model
lr_modelNew= joblib.load('lr_modelNew.pkl')
print("  Logistic Model loaded successfully.")

  Logistic Model loaded successfully.


In [117]:
import joblib

# Load the saved logistics  model
best_nb_model_New= joblib.load('Multinomial Naive Baye_model.pkl')
print("Model loaded successfully.")

Model loaded successfully.


Testing the model

In [119]:
import pandas as pd

# Load your dataset
dataset_path = 'Final_Updated__Dataset.csv'
data = pd.read_csv(dataset_path)

# Create a dictionary for symptoms 
symptoms_dict = {col: idx + 1 for idx, col in enumerate(data1.columns[:-1])}


# Print the dictionaries for verification
print("Symptoms Dictionary:", symptoms_dict)


Symptoms Dictionary: {'anxiety and nervousness': 1, 'depression': 2, 'shortness of breath': 3, 'depressive or psychotic symptoms': 4, 'sharp chest pain': 5, 'dizziness': 6, 'insomnia': 7, 'abnormal involuntary movements': 8, 'chest tightness': 9, 'palpitations': 10, 'irregular heartbeat': 11, 'breathing fast': 12, 'hoarse voice': 13, 'sore throat': 14, 'difficulty speaking': 15, 'cough': 16, 'nasal congestion': 17, 'throat swelling': 18, 'diminished hearing': 19, 'lump in throat': 20, 'throat feels tight': 21, 'difficulty in swallowing': 22, 'skin swelling': 23, 'retention of urine': 24, 'groin mass': 25, 'leg pain': 26, 'hip pain': 27, 'suprapubic pain': 28, 'blood in stool': 29, 'lack of growth': 30, 'emotional symptoms': 31, 'elbow weakness': 32, 'back weakness': 33, 'pus in sputum': 34, 'symptoms of the scrotum and testes': 35, 'swelling of scrotum': 36, 'pain in testicles': 37, 'flatulence': 38, 'pus draining from ear': 39, 'jaundice': 40, 'mass in scrotum': 41, 'white discharge f

In [60]:
# Create a dictionary with unique diseases
diseases_dict = {disease: index for index, disease in enumerate(y.unique())}

print("Diseases Dictionary:",diseases_dict)

# Reverse the diseases_dict
reverse_diseases_dict = {value: key for key, value in diseases_dict.items()}


Diseases Dictionary: {'abdominal aortic aneurysm': 0, 'abdominal hernia': 1, 'abscess of nose': 2, 'abscess of the lung': 3, 'abscess of the pharynx': 4, 'acanthosis nigricans': 5, 'acariasis': 6, 'achalasia': 7, 'acne': 8, 'actinic keratosis': 9, 'acute bronchiolitis': 10, 'acute bronchitis': 11, 'acute bronchospasm': 12, 'acute fatty liver of pregnancy (aflp)': 13, 'acute glaucoma': 14, 'acute kidney injury': 15, 'acute otitis media': 16, 'acute pancreatitis': 17, 'acute respiratory distress syndrome (ards)': 18, 'acute sinusitis': 19, 'acute stress reaction': 20, 'adhesive capsulitis of the shoulder': 21, 'adjustment reaction': 22, 'adrenal adenoma': 23, 'adrenal cancer': 24, 'alcohol abuse': 25, 'alcohol intoxication': 26, 'alcohol withdrawal': 27, 'alcoholic liver disease': 28, 'allergy': 29, 'allergy to animals': 30, 'alopecia': 31, 'alzheimer disease': 32, 'amblyopia': 33, 'amyloidosis': 34, 'amyotrophic lateral sclerosis (als)': 35, 'anal fissure': 36, 'anal fistula': 37, 'anem

with label encoding 

In [107]:
#   

def given_predicted_value(user_symptoms):
    # Initialize a zero vector for the input based on the number of symptoms
    input_vector = np.zeros(len(symptoms_dict))
    
    # Iterate over user input symptoms and fill the input vector
    for item in user_symptoms:
        if item in symptoms_dict:
            input_vector[symptoms_dict[item] - 1] = 1  # Mark the symptom as present
        else:
            print(f"Symptom '{item}' not recognized.")
            return None  # Exit if an unrecognized symptom is found
    
    # Make a prediction using the logistic regression model
    prediction = best_nb_model_New.predict([input_vector])[0]
   

    # Get the disease name from the reverse dictionary
    if prediction in reverse_diseases_dic :
        return reverse_diseases_dic[prediction]
    else:
        print(f"Prediction '{prediction}' not found in the disease dictionary.")
        return "Unknown disease"



# Without Label encoding

In [120]:


def given_predicted_value(user_symptoms):
    # Initialize a zero vector for the input based on the number of symptoms
    input_vector = np.zeros(len(symptoms_dict))
    
    # Iterate over user input symptoms and fill the input vector
    for item in user_symptoms:
        if item in symptoms_dict:
            input_vector[symptoms_dict[item] - 1] = 1  # Mark the symptom as present
        else:
            print(f"Symptom '{item}' not recognized.")
            return None  # Exit if an unrecognized symptom is found
    
    # Make a prediction using the logistic regression model
    prediction = lr_modelNew.predict([input_vector])[0]
   

    # Get the disease name from the reverse dictionary
    if prediction:
        print(f"Predicted Disease: {prediction}")
    else:
        print(f"Prediction '{prediction}' not found in the disease dictionary.")
        return "Unknown disease"



In [110]:
# Simulating user input
symptoms = input("Enter your symptoms (comma-separated): ").lower()

# Split the user's input into a list of symptoms (assuming they are comma-separated)
user_symptoms = [s.strip() for s in symptoms.split(',')]

print('Symptoms = ', user_symptoms)

# Get the predicted disease
predicted_disease = given_predicted_value(user_symptoms)

# Print the predicted disease or error message
if predicted_disease:
    print(f"Predicted Disease: {predicted_disease}")
else:
    print("Prediction could not be made. Please check your symptoms.")

Symptoms =  ['depression']
Predicted Disease: heart contusion


without labe; encoding


In [121]:

# Simulating user input
symptoms = input("Enter your symptoms (comma-separated): ").lower()

# Split the user's input into a list of symptoms (assuming they are comma-separated)
user_symptoms = [s.strip() for s in symptoms.split(',')]

print('Symptoms = ', user_symptoms)

# Get the predicted disease
given_predicted_value(user_symptoms)


Symptoms =  ['depression']
Predicted Disease: heart contusion
